sudo: required
services:
  - docker

before_install:
  - docker build -t jutkarsh079/react-test -f ./client/Dockerfile.dev ./client/Dockerfile.dev

script:
  - docker run jutkarsh079/react-test npm test -- --coverage
  
after_success:
  - docker build -t jutkarsh079/multi-client ./client/Dockerfile.dev
  - docker build -t jutkarsh079/multi-nginx ./nginx
  - docker build -t jutkarsh079/multi-server ./server
  - docker build -t jutkarsh079/multi-worker ./worker  

  